// Profit, stock valuation, item history, the audit trail.
// Reads through other modules' interfaces only — owns no data of its own.
// See docs/architecture.md.
export {
  computeTransferCost,
  computeRestaurantCostOfGoods,
  computeCanteenCostOfGoods,
  computeCountCorrection,
  getDashboardProfit,
  getRevenueProfitTrend,
  getLedgerSummary,
  getProductLedger,
  getStoreLedger,
  getNonSalesLedgerReport,
  getCashLedger,
  getActivity,
} from "./logic";
export type {
  TransferCostLine,
  TransferCostResult,
  RestaurantCostOfGoodsResult,
  CanteenCostOfGoodsResult,
  CountCorrectionResult,
  DashboardProfitResult,
  DashboardProfitLocationBreakdown,
  RevenueProfitTrendPoint,
  RevenueProfitTrendResult,
  LedgerSummaryResult,
  ProductLedgerRow,
  ProductLedgerDay,
  ProductLedgerResult,
  StoreLedgerRow,
  StoreLedgerResult,
  NonSalesLedgerRow,
  NonSalesLedgerResult,
  CashLedgerDay,
  CashTransaction,
  CashTransactionCategory,
  CashLedgerResult,
  ActivityKind,
  ActivityEntry,
  GetActivityResult,
} from "./logic";
export {
  dashboardProfitRoute,
  revenueProfitTrendRoute,
  ledgerSummaryRoute,
  productLedgerRoute,
  storeLedgerRoute,
  nonSalesLedgerRoute,
  cashLedgerRoute,
  activityRoute,
} from "./routes";
