// Profit, stock valuation, item history, the audit trail.
// Reads through other modules' interfaces only — owns no data of its own.
// See docs/architecture.md.
export {
  computeTransferCost,
  computeRestaurantCostOfGoods,
  computeCanteenCostOfGoods,
  getDashboardProfit,
  getRevenueProfitTrend,
  getExceptions,
  getLedgerSummary,
  getProductLedger,
  getStoreLedger,
  getNonSalesLedgerReport,
  getCashLedger,
  getActivity,
  getDashboardStockMovements,
  getDashboardStoreMovements,
  previewAmendment,
} from "./logic";
export type { PreviewAmendmentResult } from "./logic";
export type {
  TransferCostLine,
  TransferCostResult,
  RestaurantCostOfGoodsResult,
  CanteenCostOfGoodsResult,
  DashboardProfitResult,
  DashboardProfitLocationBreakdown,
  RevenueProfitTrendPoint,
  RevenueProfitTrendResult,
  ExceptionShortfall,
  ExceptionVoidedSale,
  GetExceptionsResult,
  LedgerSummaryResult,
  ProductLedgerRow,
  ProductLedgerDay,
  ProductLedgerResult,
  StoreLedgerRow,
  StoreLedgerResult,
  NonSalesLedgerRow,
  NonSalesLedgerResult,
  CashLedgerDay,
  CashTransaction,
  CashTransactionCategory,
  CashLedgerResult,
  ActivityKind,
  ActivityEntry,
  GetActivityResult,
  DashboardStockMovementReason,
  DashboardStockMovementRow,
  GetDashboardStockMovementsResult,
  DashboardStoreMovementRow,
  GetDashboardStoreMovementsResult,
} from "./logic";
export {
  dashboardProfitRoute,
  revenueProfitTrendRoute,
  exceptionsRoute,
  ledgerSummaryRoute,
  productLedgerRoute,
  amendLedgerRoute,
  ledgerAmendmentsRoute,
  storeLedgerRoute,
  nonSalesLedgerRoute,
  cashLedgerRoute,
  activityRoute,
  dashboardStockMovementsRoute,
  dashboardStoreMovementsRoute,
} from "./routes";
