// Products, ingredients, recipes, prices. See docs/architecture.md.

export {
  listProducts,
  findProductsByIds,
  listIngredients,
  findIngredientsByIds,
  listCategories,
  listActiveAssets as listAssets,
} from "./queries";
export {
  createProduct,
  updateProduct,
  deactivateProduct,
  reactivateProduct,
  createIngredient,
  updateIngredient,
  deactivateIngredient,
  reactivateIngredient,
  recordIngredientCost,
  recordProductCost,
  createRecipe,
  getCurrentRecipe,
  getRecipeAt,
  listRecipeVersions,
  createAsset,
  updateAssetQuantity,
  linkAssetExpense,
  retireAsset,
  createCategory,
  updateCategory,
  deactivateCategory,
  reactivateCategory,
} from "./logic";
export type { Product, ProductKind, Ingredient, Recipe, RecipeWithCost, Asset, Category } from "./schema";
export {
  catalogueRoute,
  activeProductsRoute,
  activeIngredientsRoute,
  createProductRoute,
  updateProductRoute,
  setProductActiveRoute,
  createIngredientRoute,
  updateIngredientRoute,
  setIngredientActiveRoute,
  createRecipeRoute,
  recipeVersionsRoute,
  createAssetRoute,
  updateAssetQuantityRoute,
  linkAssetExpenseRoute,
  retireAssetRoute,
  createCategoryRoute,
  updateCategoryRoute,
  setCategoryActiveRoute,
} from "./routes";
