// Generates plain SQL (no Prisma/DB connection needed) for the production
// catalog import, from the same mapping rules as import-v2-catalog.ts:
//
//   supply_type -> locationId (owner-confirmed):
//     restaurant_only, canteen_supplied -> restaurant
//     canteen_independent               -> canteen
//   kind inferred from category (owner-confirmed):
//     meals -> cooked_food, cyber -> service, else -> goods
//   prices are plain whole shillings, NOT cents (src/shared/money.ts, BUG-11)
//
// Placeholders {{RESTAURANT_ID}} / {{CANTEEN_ID}} must be substituted with
// the real Location ids from the target database before running.
//
// Usage: npx tsx scripts/generate-v2-catalog-sql.ts > scripts/v2-catalog-import.sql

import { randomUUID } from "crypto";
import { readFileSync } from "fs";

function kindForCategory(category: string): string {
  if (category === "meals") return "cooked_food";
  if (category === "cyber") return "service";
  return "goods";
}

function locationPlaceholderFor(supplyType: string): string {
  if (supplyType === "canteen_independent") return "{{CANTEEN_ID}}";
  return "{{RESTAURANT_ID}}"; // restaurant_only, canteen_supplied
}

// Owner-confirmed: a name that appears twice with different supply_types
// (e.g. "Dasani 500ml" at both restaurant_only and canteen_independent) is
// two real, independently priced/stocked products, not a duplicate — the
// unique constraint on products.name means both need distinct names.
function disambiguateDuplicateNames<T extends { name: string; supply_type: string }>(items: T[]): T[] {
  const counts = new Map<string, number>();
  for (const item of items) counts.set(item.name, (counts.get(item.name) ?? 0) + 1);

  return items.map((item) => {
    if ((counts.get(item.name) ?? 0) < 2) return item;
    const suffix = item.supply_type === "canteen_independent" ? "Canteen" : "Restaurant";
    return { ...item, name: `${item.name} (${suffix})` };
  });
}

function toShillings(decimalString: string): number | null {
  const value = Number(decimalString);
  if (!Number.isFinite(value)) return null;
  return Math.round(value);
}

function sqlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function sqlNumOrNull(n: number | null): string {
  return n === null ? "NULL" : String(n);
}

function main() {
  const raw = readFileSync("scripts/v2-catalog-export.json", "utf-8");
  const data = JSON.parse(raw);
  data.items = disambiguateDuplicateNames(data.items);

  const lines: string[] = [];
  lines.push("-- Generated by scripts/generate-v2-catalog-sql.ts — do not hand-edit.");
  lines.push("-- Substitute {{RESTAURANT_ID}} / {{CANTEEN_ID}} with real Location ids first.");
  lines.push("BEGIN;");
  lines.push("");

  const categoryNames: string[] = [...new Set(data.items.map((i: { category: string }) => i.category))];
  const categoryIdByName: Record<string, string> = {};
  lines.push("-- Categories");
  for (const name of categoryNames) {
    const id = randomUUID();
    categoryIdByName[name] = id;
    lines.push(
      `INSERT INTO categories (id, name, active, "createdAt") VALUES (${sqlString(id)}, ${sqlString(name)}, true, now());`,
    );
  }
  lines.push("");

  lines.push("-- Products");
  for (const item of data.items) {
    const id = randomUUID();
    const kind = kindForCategory(item.category);
    const locationPlaceholder = locationPlaceholderFor(item.supply_type);
    const priceMinor = sqlNumOrNull(toShillings(item.selling_price));
    const rawCost = toShillings(item.buying_price);
    const lastKnownCostMinor = sqlNumOrNull(rawCost && rawCost > 0 ? rawCost : null);
    const lowStockLevel = sqlNumOrNull(
      item.low_stock_threshold != null ? Math.round(Number(item.low_stock_threshold)) : null,
    );
    const categoryId = sqlString(categoryIdByName[item.category]);

    lines.push(
      `INSERT INTO products (id, name, kind, "priceMinor", "lastKnownCostMinor", "lowStockLevel", active, "categoryId", "locationId", "createdAt") ` +
        `VALUES (${sqlString(id)}, ${sqlString(item.name)}, ${sqlString(kind)}, ${priceMinor}, ${lastKnownCostMinor}, ${lowStockLevel}, ${item.active}, ${categoryId}, ${locationPlaceholder}, now());`,
    );
  }
  lines.push("");

  lines.push("-- Ingredients");
  for (const ing of data.ingredients) {
    const id = randomUUID();
    const rawCost = toShillings(ing.buying_price);
    const lastKnownCostMinor = sqlNumOrNull(rawCost && rawCost > 0 ? rawCost : null);
    const lowStockLevel = sqlNumOrNull(
      ing.low_stock_threshold != null ? Math.round(Number(ing.low_stock_threshold)) : null,
    );

    lines.push(
      `INSERT INTO ingredients (id, name, "unitOfMeasure", "lastKnownCostMinor", "lowStockLevel", active, "createdAt") ` +
        `VALUES (${sqlString(id)}, ${sqlString(ing.name)}, ${sqlString(ing.unit)}, ${lastKnownCostMinor}, ${lowStockLevel}, ${ing.active}, now());`,
    );
  }
  lines.push("");
  lines.push("COMMIT;");

  console.log(lines.join("\n"));
}

main();
